version: '2'

services:
  redis-6379:
    image: redis
    container_name: redis-6379
    restart: always
    network_mode: 'host'
    volumes:
      - ./6379/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./6379/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6380:
    image: redis
    container_name: redis-6380
    restart: always
    network_mode: 'host'
    volumes:
      - ./6380/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./6380/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6381:
    image: redis
    container_name: redis-6381
    restart: always
    network_mode: 'host'
    volumes:
      - ./6381/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./6381/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6382:
    image: redis
    container_name: redis-6382
    restart: always
    network_mode: 'host'
    volumes:
      - ./6382/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./6382/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

 