version: '2'

services:
  redis-6371:
    image: redis
    container_name: redis-6371
    restart: always
    network_mode: 'host'
    volumes:
      - /home/pcbackend04/Documents/devops/redis-cluster/6371/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/pcbackend04/Documents/devops/redis-cluster/6371/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6372:
    image: redis
    container_name: redis-6372
    restart: always
    network_mode: 'host'
    volumes:
      - /home/pcbackend04/Documents/devops/redis-cluster/6372/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/pcbackend04/Documents/devops/redis-cluster/6372/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6373:
    image: redis
    container_name: redis-6373
    restart: always
    network_mode: 'host'
    volumes:
      - /home/pcbackend04/Documents/devops/redis-cluster/6373/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/pcbackend04/Documents/devops/redis-cluster/6373/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6374:
    image: redis
    container_name: redis-6374
    restart: always
    network_mode: 'host'
    volumes:
      - /home/pcbackend04/Documents/devops/redis-cluster/6374/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/pcbackend04/Documents/devops/redis-cluster/6374/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6375:
    image: redis
    container_name: redis-6375
    restart: always
    network_mode: 'host'
    volumes:
      - /home/pcbackend04/Documents/devops/redis-cluster/6375/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/pcbackend04/Documents/devops/redis-cluster/6375/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6376:
    image: redis
    container_name: redis-6376
    restart: always
    network_mode: 'host'
    volumes:
      - /home/pcbackend04/Documents/devops/redis-cluster/6376/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/pcbackend04/Documents/devops/redis-cluster/6376/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
